aws:
  bucket: pix-datalake-benjivoid

paths:
  bronze: bronze
  silver: silver
  gold: gold

defaults:
  database: "2025-01"
  top: 100000

athena:
  database: pix_dw
  workgroup: primary
  output_location: "s3://pix-datalake-benjivoid/athena-results/"
  