pix_estatisticas_transacoes:
  endpoint: "EstatisticasTransacoesPix(Database=@Database)"
  param_name: "Database"
  bronze_parquet: "estatisticas_transacoes_pix"
  bronze_raw: "estatisticas_transacoes_pix_raw"

  silver:
    int_cols: ["anomes", "quantidade"]

    float_prefixes: ["valor"]

    int_prefixes: []

    required:
      - anomes
      - valor
      - quantidade

    normalize_text:
      - pag_pfpj
      - rec_pfpj
      - pag_regiao
      - rec_regiao
      - pag_idade
      - rec_idade
      - formainiciacao
      - natureza
      - finalidade
  athena:
    silver_table: estatisticas_transacoes_pix_silver

pix_municipio:
  endpoint: "TransacoesPixPorMunicipio(DataBase=@DataBase)"
  param_name: "DataBase"
  bronze_parquet: "transacoes_pix_por_municipio"
  bronze_raw: "transacoes_pix_por_municipio_raw"

  silver:
    int_cols: ["municipio_ibge", "estado_ibge"]
    float_prefixes: ["vl_"]
    int_prefixes: ["qt_"]
    required: ["municipio_ibge", "estado_ibge", "municipio", "estado"]
    normalize_text: ["municipio", "estado", "regiao", "sigla_regiao"]
  athena:
    silver_table: transacoes_pix_por_municipio_silver

pix_fraudes_med:
  endpoint: "EstatisticasFraudesPix(Database=@Database)"
  param_name: "Database"
  bronze_parquet: "estatisticas_fraudes_pix"
  bronze_raw: "estatisticas_fraudes_pix_raw"

  silver:
    int_cols:
      - anomes
      - qtdepixcontestados
      - qtdecontestacoesaceitas
      - qtdecontestacoesrejeitadas
      - qtdeusuarioscommarcacoesdefraude
      - qtdechavespixcommarcacoesdefraude
      - quantidadedevolvidaintegralmentepormeiodomed
      - quantidadedevolvidaparcialmentepormeiodomed
      - quantidadedenaodevolvidossaldoinsuficiente
      - quantidadedenaodevolvidoscontaencerrada
      - quantidadedenaodevolvidosmotivosdiversos
      - qtdepixbloqueadoscautelarmenteeliberados
      - qtdepixbloqueadoscautelarmenteedevolvidos

    float_prefixes: ["valorpix", "percentual"]

    int_prefixes: []

    required:
      - anomes

    normalize_text: []
  athena:
    silver_table: estatisticas_fraudes_pix_silver

pix_chaves:
  endpoint: "ChavesPix(Data=@Data)"
  param_name: "Data"
  bronze_parquet: "estoque_chaves_pix"
  bronze_raw: "estoque_chaves_pix_raw"

  partition:
    type: "day"
    column: "data_part"
    format: "%Y%m%d"

  silver:
    int_cols: ["qtdchaves"]

    float_prefixes: []
    int_prefixes: []

    required: ["data", "ispb", "tipochave", "qtdchaves"]

    normalize_text:
      - ispb
      - nome
      - naturezausuario
      - tipochave
  athena:
    silver_table: estoque_chaves_pix_silver